### PR TITLE
Create GitHub action for Black

### PR DESCRIPTION
**Pull request by vanillajonathan**
Action integration for the Python code formatter Black.

https://black.readthedocs.io/en/stable/

### CODE REVIEW

**Comment by hugolabe** [comment]
I don't know what use this is...

**Comment by vanillajonathan** [comment]
The link explains it. Every time there is a commit to this repository a GitHub Action is invoked which formats the Python code with the Python code formatter Black which ensures the code is properly and consistently formatted according to the code style that is popular in the Python community.

**Comment by hugolabe** [comment]
Thanks for the suggestion. But the truth is, I don't like the idea that the code can be modified automatically.

**Comment by vanillajonathan** [comment]
The great thing about Black is that you never need to think about code style, it handles it automatically, and it makes it easier for contributors to contribute since their code just gets automatically formatted so all the code in the project is in the same code style, and the project is in the same code style as the Python community uses, because Black follows [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/).

I think you should definitely strongly consider to adopt this.

**Comment by vanillajonathan** [comment]
You can also try out Black online at:
https://black.vercel.app/

Or run it locally:

    pip3 install black
    black {source_file_or_directory}...

**Pull request closed without merging**
