### PR TITLE
Shutdown signal to save settings, quit if no tabs

### PR DESCRIPTION
**Pull request by kra-mo**
Use the 'shutdown' signal to save settings, quit with Ctrl+W if there are no other tabs open

### CODE REVIEW

**Comment by hugolabe** [comment]
The fact that the last tab cannot be closed (but requires closing the application) is a design decision. I prefer it this way.

**Comment by kra-mo** [comment]
Well, this is inconsistent with other GNOME applications. But even then, what's wrong with the other part of the PR?

**Comment by hugolabe** [comment]
> Well, this is inconsistent with other GNOME applications.

Not all applications have this behavior (Builder, Text Editor...). Browsers do have it, but the vision I have for Wike is not to replicate the operation of one of them.

> But even then, what's wrong with the other part of the PR?

I thought PR was focused only on this topic. Is there a problem with how the app's output is currently managed? It seems to work fine...

**Comment by kra-mo** [comment]
> Not all applications have this behavior (Builder, Text Editor...). Browsers do have it, but the vision I have for Wike is not to replicate the operation of one of them.

Builder is an IDE, I would not expect it to. But Text Editor does, so does Nautilus, Apostrophe and probably many others. And this behavior is encouraged by at least the Circle committee, at least I have been asked to include it even for a single-window app.

> I thought PR was focused only on this topic. Is there a problem with how the app's output is currently managed? It seems to work fine...

It works, but its a hack.

**Pull request closed without merging**
