### PR TITLE
Two small fixes

### PR DESCRIPTION
**Pull request by sabriunal**
- UI: Add a tooltip to the pin sidebar action
- UI: Use ellipses instead of three dots

### CODE REVIEW

**Comment by hugolabe** [comment]
Thanks @sabriunal !

> * UI: Add a tooltip to the pin/unpin action

I decided not to put the Pin Button tooltip because it seems to me that its function is very obvious and I am in favor of using as few tooltips as possible.
What do you think?

> * UI: Use ellipses instead of three dots

Ok!

**Comment by sabriunal** [comment]
I use Breeze theme from KDE. Two buttons seem missing. Still I can know the first one is sidebar from tooltip. The second one have no icon and no tooltip. There is no way to know what this button do. Also, other tabs (history, bookmarks, languages, contents) have tooltips except this button.

Ekran Görüntüsü - 2023-04-01 12-47-46

**Comment by hugolabe** [comment]
Ok, we put it.

It's strange, both icons are part of GNOME's pre-installed system icons.

One last thing: Wouldn't `Pin Sidebar` be clearer for the tooltip? It doesn't seem to me necessary to specify the opposite action.

**Comment by sabriunal** [comment]
OK. I chaged the string.

**Comment by camelCaseNick** [comment]
>     * UI: Use ellipses instead of three dots

What about applying this change there as well: https://github.com/hugolabe/Wike/blob/a2e9c333608ee778050b1e4af5e55b7f30415e60/data/com.github.hugolabe.Wike.metainfo.xml.in#L20

**Comment by hugolabe** [comment]
> OK. I chaged the string.

Thanks!

**Comment by hugolabe** [comment]
> > * UI: Use ellipses instead of three dots
> 
> What about applying this change there as well:
> 
> https://github.com/hugolabe/Wike/blob/a2e9c333608ee778050b1e4af5e55b7f30415e60/data/com.github.hugolabe.Wike.metainfo.xml.in#L20

Yes. Since I have to update the POT template, I take the opportunity to change it.

**Pull request merged**
