### PR TITLE
removed debian/ files

### PR DESCRIPTION
**Pull request by werdahias**
For packaging, the debian folder should go to a separate branch. I am working on getting wike into the debian repos. Maybe just move the debian/ folder to a separate ubuntu branch.

Cheers

### CODE REVIEW

**Comment by hugolabe** [comment]
I don’t know how packaging for Debian works. This folder was created by @apandada1, so I think he should say if he agrees with this.

**Comment by apandada1** [comment]
The debian directory is required to automatically build the app in the Launchpad ppa (which is a convenient way to install the app before it goes to the Debian/Ubuntu repositories), whenever a new version is released.

If you want to submit it to Debian, you can remove `debian/` directory locally, and use your own copy of it. But please don't remove it from the main repo until it is available in the repositories (then the PPA will not be required).

**Comment by CountOmega** [comment]
@apandada1 k, will leave this open until wike is in the repos

**Comment by werdahias** [comment]
@hugolabe @apandada1 wike just got accepted into debian unstable. So the debian/ folder is obsolete

**Comment by apandada1** [comment]
Great. @hugolabe feel free to delete the directory.

On 9/25/22, werdahias ***@***.***> wrote:
> @hugolabe @apandada1 wike just got accepted into debian unstable. So the
> debian/ folder is obsolete
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/hugolabe/Wike/pull/80#issuecomment-1257260063
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
---
Archisman Panigrahi,
Graduate Student,
Department of Physics,
Massachusetts Institute of Technology

**Pull request closed without merging**
